# Generated by Django 5.1.3 on 2024-11-27 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('horarios', '0001_initial'),
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, related_name='horarios_estudiante', to='estudiantes.estudiante'),
        ),
        migrations.AddField(
            model_name='horario',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_profesor', to='profesores.profesor'),
        ),
    ]
