# Generated by Django 5.1.3 on 2024-11-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='estudiantes',
            field=models.ManyToManyField(related_name='materias_matriculadas', to='estudiantes.estudiante'),
        ),
    ]
